version: "3.8"
services:
  server:
    container_name: server
    image: app/server
    build:
      dockerfile: Dockerfile
      context: server
    ports:
      - "3300:3300"
  client:
    container_name: client
    image: app/client
    build:
      dockerfile: Dockerfile
      context: client
    ports:
      - "3000:3000"