# Dockerfile

# Use an existing node alpine image as a base image.
FROM node:latest

# Set the working directory.
WORKDIR /app/server

# Copy the package.json file.
COPY package.json .

# Install application dependencies.
RUN npm install

# Copy the rest of the application files.
COPY . .

# Expose the port.
EXPOSE 3300

# Run the application.
CMD npm run start